[package]
name = "nox"
version = "0.1.0"
authors = ["0xd34d10cc <0xd34d10cc@gmail.com>"]
edition = "2018"

[dependencies]
nom = "5.0.1"
structopt = "0.3.5"
rustyline = "5.0.5"

[features]
generated = []
deep-expressions = []