// This file was generated by statements.py

use super::run;
#[test]
fn test001() {
    run(
        "
        read (x);
        read (y);
        z := x*y*3;
        write (z)
        "
         ,
        &[5, 6],
        &[90],
        2
    );
}

#[test]
fn test002() {
    run(
        "
        read (x);
        read (y);
        z := y*y;
        write (x+z)
        "
         ,
        &[5, 6],
        &[41],
        2
    );
}

#[test]
fn test003() {
    run(
        "
        read (x);
        read (y);
        write (x-y);
        write (x/y);
        write (x%y)
        "
         ,
        &[10, 3],
        &[7, 3, 1],
        2
    );
}

#[test]
fn test004() {
    run(
        "
        read (x);
        read (y);
        z := ((x + y) + (x - y)) + ((x - y) - (x + y));
        write (z)
        "
         ,
        &[10, 5],
        &[10],
        2
    );
}

#[test]
fn test005() {
    run(
        "
        read (x);
        read (y);
        z := ((x + y) + (x - y)) + ((x - y) - (x / y));
        write (z)
        "
         ,
        &[6, 7],
        &[11],
        2
    );
}

#[test]
fn test006() {
    run(
        "
        read (x);
        read (y);
        z := x < y;
        write (z);
        z := x <= y;
        write (z);
        z := x == y;
        write (z);
        z := x != y;
        write (z);
        z := x >= y;
        write (z);
        z := x > y;
        write (z)
        "
         ,
        &[-6, 7],
        &[1, 1, 0, 1, 0, 0],
        2
    );
}

#[test]
fn test007() {
    run(
        "
        x := 1;
        y := 2;
        z := x - y - 3;
        write (z)
        "
         ,
        &[],
        &[-4],
        0
    );
}

#[test]
fn test008() {
    run(
        "
        z := 0 - 1 - 2 - 3 - 4 - 5 - 6 - 7 - 8 - 9;
        write (z)
        "
         ,
        &[],
        &[-45],
        0
    );
}

